// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrubwsefcatatcrygbfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZydWJ3c2VmY2F0YXRjcnlnYmZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyNTIyOTMsImV4cCI6MjA3NDgyODI5M30.R86k36wbxZdzKpiI8pQzbLTwGo6r9o_EbgyjYwQVsBU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});